//*
//*
//*
//*
//*
//*
//*
//*
//*
//*
//*
//* When working in this document, save the date and rows affected for any changes

//* 160 rows
//* 4/20/2024
//* modeling.utils
const recordDetailsObj = {
  identifiers: {
    FIPS: { label: 'FIPS', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    AttomId: { label: 'Attom ID', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    PMXPropertyId: { label: 'Prop Mix ID', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    CoreLogicClip: { label: 'CoreLogicClip', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  lot: {
    County: { label: 'County', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Municipality: { label: 'Municipality', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LegalSubdivisionName: { label: 'Legal Subdivision Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    ParcelNumber: { label: 'Parcel Number', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Latitude: { label: 'Latitude', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Longitude: { label: 'Longitude', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LotSizeAcres: { label: 'Lot Size Acres', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LotSizeSquareFeet: { label: 'Lot Size Square Feet', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Zoning: { label: 'Zoning', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    CountyLandUseCode: { label: 'County Land Use Code', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    BelowGradeTotalArea: { label: 'Below Grade Total Area', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    BelowGradeFinishedArea: { label: 'Below Grade Finished Area', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LandUseCode: { label: 'Land Use Code', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    CountyUseCode: { label: 'County Use Code', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxLot: { label: 'Tax Lot', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxBlock: { label: 'Tax Block', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxCodeArea: { label: 'Tax Code Area', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    CensusTractId: { label: 'Census Tract ID', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  address: {
    StreetAddressOneLine: { label: 'Street Address One Line', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    StreetAddressLine1: { label: 'Street Address Line 1', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    StreetAddressLine2: { label: 'Street Address Line 2', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    StreetNumber: { label: 'Street Number', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    UnitPrefix: { label: 'Unit Prefix', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    UnitNumber: { label: 'Unit Number', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    StreetDirPrefix: { label: 'Street Direction Prefix', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    StreetName: { label: 'Street Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    StreetSuffix: { label: 'Street Suffix', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    StreetDirSuffix: { label: 'Street Direction Suffix', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    City: { label: 'City', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    StateOrProvince: { label: 'StateOrProvince', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    PostalCode: { label: 'Postal Code', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    PostalCodePlus4: { label: 'Postal Code Plus 4', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  summary: {
    WaterSource: { label: 'Water Source', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    SewerType: { label: 'Sewer Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    SchoolDistrict: { label: 'School District', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    PropertyType: { label: 'Property Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    PropertySubType: { label: 'Property Sub Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    QuitClaimFlag: { label: 'Quit Claim Flag', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    REOflag: { label: 'Foreclosure Flag', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    DistressYN: { label: 'Distress', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  sale: {
    LeaseholdOrFeeSimple: { label: 'Leasehold Or Fee Simple', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LastSaleRecordingDate: { label: 'Last Sale Recording Date', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LastSaleContractDate: { label: 'Last Sale Contract Date', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LastSaleDate: { label: 'Last Sale Date', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    ClosePrice: { label: 'Close Price', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    ClosePriceDescription: { label: 'Close Price Description', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LastSaleTransactionId: { label: 'Last Sale Transaction ID', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LastSaleBuyerName: { label: 'Last Sale Buyer Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    SaleDocType: { label: 'Sale Document Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LastSaleRecordingDocumentId: { label: 'Last Sale Recording Document ID', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LastSaleSeller2FullName: { label: 'Last Sale Seller 2 Full Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LastSaleSeller1FullName: { label: 'Last Sale Seller 1 Full Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  living: {
    BuildingAreaTotal: { label: 'Building Area Total', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    GrossArea: { label: 'Gross Area', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    LivingArea: { label: 'Living Area', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Stories: { label: 'Stories', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    RoomsTotal: { label: 'Rooms', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    BedroomsTotal: { label: 'Bedrooms', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    BathroomsFull: { label: 'Bathrooms Full', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    BathroomsTotalInteger: { label: 'Bathrooms Total', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    FireplacesTotal: { label: 'Fireplaces', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Heating: { label: 'Heating', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Cooling: { label: 'Cooling', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    PoolType: { label: 'Pool Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  building: {
    BuildingQualityScore: { label: 'Building Quality Score', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    BuildingCondition: { label: 'Building Condition', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    YearBuilt: { label: 'Year Built', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    YearBuiltEffective: { label: 'Year Built Effective', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    NumberOfBuildings: { label: 'Number Of Buildings', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    NumberOfUnitsTotal: { label: 'Number Of Units Total', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    ArchitecturalStyle: { label: 'Architectural Style', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    ConstructionType: { label: 'Construction Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    FrameType: { label: 'Frame Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    ExteriorWallsType: { label: 'Exterior Walls Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    InteriorWallsType: { label: 'Interior Walls Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    RoofType: { label: 'Roof Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    RoofCoverType: { label: 'Roof Cover Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    CarStorageType: { label: 'Car Storage Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    GarageSpaces: { label: 'Garage Spaces', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    GarageArea: { label: 'Garage Area', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    ParkingSpaces: { label: 'Parking Spaces', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  assessment: {
    AssessedYear: { label: 'Assessed Year', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    AssessedValue: { label: 'Assessed Value', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    AssessedLandValue: { label: 'Assessed Land Value', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    AssessedImprovementValue: { label: 'Assessed Improvement Value', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    // MarketValue: { label: 'Market Value', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    // MarketLandValue: { label: 'Market Land Value', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    // MarketImprovementValue: { label: 'Market Improvement Value', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    // LandValue: { label: 'Land Value', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    // ImprovementsValue: { label: 'Improvements Value', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    AssessorsMapReference: { label: 'Assessors Map Reference', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  tax: {
    TaxYear: { label: 'Tax Year', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxAnnualAmount: { label: 'Tax Annual Amount', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    OwnerOccupied: { label: 'Owner Occupied', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionHomestead: { label: 'Tax Exemption Homestead', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionVeteran: { label: 'Tax Exemption Veteran', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionDisabled: { label: 'Tax Exemption Disabled', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionWidow: { label: 'Tax Exemption Widow', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionSenior: { label: 'Tax Exemption Senior', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionSchoolCollege: { label: 'Tax Exemption School/College', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionReligious: { label: 'Tax Exemption Religious', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionWelfare: { label: 'Tax Exemption Welfare', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionPublicUtility: { label: 'Tax Exemption Public Utility', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionCemetery: { label: 'Tax Exemption Cemetery', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionHospital: { label: 'Tax Exemption Hospital', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxExemptionLibrary: { label: 'Tax Exemption Library', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    TaxInitialDeliquencyYear: { label: 'Tax Initial Delinquency Year', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  owner1: {
    Owner1OwnershipRights: { label: 'Owner One Ownership Rights', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Owner1IsCorporation: { label: 'Owner One Is Corporation', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    CorporateIndicator: { label: 'Corporate Indicator', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Owner1FullName: { label: 'Owner One Full Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Owner1LastName: { label: 'Owner One Last Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Owner1FirstName: { label: 'Owner One First Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  owner2: {
    Owner2IsCorporation: { label: 'Owner Two Is Corporation', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Owner2FullName: { label: 'Owner Two Full Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Owner2LastName: { label: 'Owner Two Last Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
    Owner2FirstName: { label: 'Owner Two First Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: '' },
  },
  primaryMortgage: {
    PrimaryMortgageAmount: { label: 'Primary Mortgage Amount', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    PrimaryMortgageInterestRate: { label: 'Primary Mortgage Interest Rate', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    PrimaryLenderName: { label: 'Primary Lender Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    PrimaryMortgageStartDate: { label: 'Primary Mortgage Start Date', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    PrimaryLoanType: { label: 'Primary Loan Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    PrimaryMortgageTerm: { label: 'Primary Mortgage Term', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    PrimaryMortgageDueDate: { label: 'Primary Mortgage Due Date', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    TitleCompany: { label: 'Title Company', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    OwnershipRights: { label: 'Ownership Rights', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    BorrowerRelationship: { label: 'Borrower Relationship', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    MortgageTransactionDescription: { label: 'Mortgage Transaction Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    DeedCategoryDescriprion: { label: 'Deed Category', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
  },
  secondaryMortgage: {
    SecondaryMortgageAmount: { label: 'Secondary Mortgage Amount', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    SecondaryLenderName: { label: 'Secondary Lender Name', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    SecondaryMortgageRecordingDate: { label: 'Secondary Mortgage Recording Date', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    SecondaryLoanType: { label: 'Secondary Loan Type', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    SecondaryMortgageTerm: { label: 'Secondary Mortgage Term', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
    SecondaryMortgageDueDate: { label: 'Secondary Mortgage Due Date', currentValue: '', originalValue: '', status: 'inactive', publicRecordValue: ''},
  },
}




//************** */
//************** */
//*** Changes to the structure of the data model must also be updated in the: */
//*** modeling.utils file where it is creating the mappedVendorData return obj and/or where it parses vendor data */
//*** Data Object google docs file */
//************** */
//************** */
//* 160 rows
//* 4/20/2024
const mortgageDataModel = {
  identifiers: {
    FIPS: { label: 'FIPS', active: true, assignedTier: 'three', tags: []},
    AttomId: { label: 'Attom ID', active: true, assignedTier: 'three', tags: []},
    PMXPropertyId: { label: 'Prop Mix ID', active: true, assignedTier: 'three', tags: []},
    CoreLogicClip: { label: 'CoreLogicClip', active: true, assignedTier: 'three', tags: [] },
  },
  lot: {
    County: { label: 'County', active: true, assignedTier: 'two', tags: ['rezoning']},
    Municipality: { label: 'Municipality', active: true, assignedTier: 'one', tags: ['subdivision']},
    LegalSubdivisionName: { label: 'Legal Subdivision Name', active: true, assignedTier: 'two', tags: ['subdivision']},
    ParcelNumber: { label: 'Parcel Number', active: true, assignedTier: 'two', tags: ['subdivision']},
    Latitude: { label: 'Latitude', active: true, assignedTier: 'two', tags: ['addSubUnits', 'subdivision', 'improvements']},
    Longitude: { label: 'Longitude', active: true, assignedTier: 'two', tags: ['addSubUnits', 'subdivision', 'improvements']},
    LotSizeAcres: { label: 'Lot Size Acres', active: true, assignedTier: 'two', tags: ['subdivision']},
    LotSizeSquareFeet: { label: 'Lot Size Square Feet', active: true, assignedTier: 'two', tags: ['subdivision']},
    Zoning: { label: 'Zoning', active: true, assignedTier: 'two', tags: ['rezoning']},
    CountyLandUseCode: { label: 'County Land Use Code', active: true, assignedTier: 'two', tags: ['rezoning']},
    BelowGradeTotalArea: { label: 'Below Grade Total Area', active: true, assignedTier: 'two', tags: ['subdivision']},
    BelowGradeFinishedArea: { label: 'Below Grade Finished Area', active: true, assignedTier: 'two', tags: ['subdivision']},
    LandUseCode: { label: 'Land Use Code', active: true, assignedTier: 'two', tags: ['rezoning', 'improvements']},
    CountyUseCode: { label: 'County Use Code', active: true, assignedTier: 'two', tags: ['rezoning', 'improvements']},
    TaxLot: { label: 'Tax Lot', active: true, assignedTier: 'two', tags: ['subdivision', 'rezoning']},
    TaxBlock: { label: 'Tax Block', active: true, assignedTier: 'two', tags: ['subdivision', 'rezoning']},
    TaxCodeArea: { label: 'Tax Code Area', active: true, assignedTier: 'two', tags: ['subdivision', 'rezoning']},
    CensusTractId: { label: 'Census Tract ID', active: true, assignedTier: 'three', tags: []},
  },
  address: {
    StreetAddressOneLine: { label: 'Street Address One Line', active: true, assignedTier: 'one', tags: ['subdivision']},
    StreetAddressLine1: { label: 'Street Address Line 1', active: true, assignedTier: 'one', tags: ['subdivision']},
    StreetAddressLine2: { label: 'Street Address Line 2', active: true, assignedTier: 'one', tags: ['subdivision']},
    StreetNumber: { label: 'Street Number', active: true, assignedTier: 'one', tags: ['subdivision']},
    UnitPrefix: { label: 'Unit Prefix', active: true, assignedTier: 'one', tags: ['subdivision']},
    UnitNumber: { label: 'Unit Number', active: true, assignedTier: 'one', tags: ['subdivision']},
    StreetDirPrefix: { label: 'Street Direction Prefix', active: true, assignedTier: 'one', tags: ['subdivision']},
    StreetName: { label: 'Street Name', active: true, assignedTier: 'one', tags: ['subdivision']},
    StreetSuffix: { label: 'Street Suffix', active: true, assignedTier: 'one', tags: ['subdivision']},
    StreetDirSuffix: { label: 'Street Direction Suffix', active: true, assignedTier: 'one', tags: ['subdivision']},
    City: { label: 'City', active: true, assignedTier: 'one', tags: ['subdivision']},
    StateOrProvince: { label: 'StateOrProvince', active: true, assignedTier: 'one', tags: ['subdivision']},
    PostalCode: { label: 'Postal Code', active: true, assignedTier: 'one', tags: ['subdivision']},
    PostalCodePlus4: { label: 'Postal Code Plus 4', active: true, assignedTier: 'one', tags: ['subdivision']},
  },
  summary: {
    WaterSource: { label: 'Water Source', active: true, assignedTier: 'two', tags: ['improvements']},
    SewerType: { label: 'Sewer Type', active: true, assignedTier: 'two', tags: ['improvements']},
    SchoolDistrict: { label: 'School District', active: true, assignedTier: 'three', tags: []},
    PropertyType: { label: 'Property Type', active: true, assignedTier: 'two', tags: ['rezoning']},
    PropertySubType: { label: 'Property Sub Type', active: true, assignedTier: 'one', tags: ['addSubUnits', 'improvements']},
    QuitClaimFlag: { label: 'Quit Claim Flag', active: true, assignedTier: 'one', tags: ['transfer']},
    REOflag: { label: 'Foreclosure Flag', active: true, assignedTier: 'one', tags: ['transfer', 'distress']},
    DistressYN: { label: 'Distress', active: true, assignedTier: 'two', tags: ['distress']},
  },
  sale: {
    LeaseholdOrFeeSimple: { label: 'Leasehold Or Fee Simple', active: true, assignedTier: 'one', tags: ['transfer']},
    LastSaleRecordingDate: { label: 'Last Sale Recording Date', active: true, assignedTier: 'one', tags: ['transfer']},
    LastSaleContractDate: { label: 'Last Sale Contract Date', active: true, assignedTier: 'one', tags: ['transfer']},
    LastSaleDate: { label: 'Last Sale Date', active: true, assignedTier: 'one', tags: ['transfer']},
    ClosePrice: { label: 'Close Price', active: true, assignedTier: 'one', tags: ['transfer']},
    ClosePriceDescription: { label: 'Close Price Description', active: true, assignedTier: 'one', tags: ['transfer']},
    LastSaleTransactionId: { label: 'Last Sale Transaction ID', active: true, assignedTier: 'one', tags: ['transfer']},
    LastSaleBuyerName: { label: 'Last Sale Buyer Name', active: true, assignedTier: 'one', tags: ['transfer']},
    SaleDocType: { label: 'Sale Document Type', active: true, assignedTier: 'one', tags: ['transfer']},
    LastSaleRecordingDocumentId: { label: 'Last Sale Recording Document ID', active: true, assignedTier: 'one', tags: ['transfer']},
    LastSaleSeller2FullName: { label: 'Last Sale Seller 2 Full Name', active: true, assignedTier: 'one', tags: ['transfer']},
    LastSaleSeller1FullName: { label: 'Last Sale Seller 1 Full Name', active: true, assignedTier: 'one', tags: ['transfer']},
  },
  living: {
    BuildingAreaTotal: { label: 'Building Area Total', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    GrossArea: { label: 'Gross Area', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    LivingArea: { label: 'Living Area', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    Stories: { label: 'Stories', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    RoomsTotal: { label: 'Rooms', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    BedroomsTotal: { label: 'Bedrooms', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    BathroomsFull: { label: 'Bathrooms Full', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    BathroomsTotalInteger: { label: 'Bathrooms Total', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    FireplacesTotal: { label: 'Fireplaces', active: true, assignedTier: 'three', tags: ['improvements']},
    Heating: { label: 'Heating', active: true, assignedTier: 'three', tags: ['improvements']},
    Cooling: { label: 'Cooling', active: true, assignedTier: 'three', tags: ['improvements']},
    PoolType: { label: 'Pool Type', active: true, assignedTier: 'two', tags: ['improvements']},
  },
  building: {
    BuildingQualityScore: { label: 'Building Quality Score', active: true, assignedTier: 'two', tags: ['improvements']},
    BuildingCondition: { label: 'Building Condition', active: true, assignedTier: 'two', tags: []},
    YearBuilt: { label: 'Year Built', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    YearBuiltEffective: { label: 'Year Built Effective', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    NumberOfBuildings: { label: 'Number Of Buildings', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    NumberOfUnitsTotal: { label: 'Number Of Units Total', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    ArchitecturalStyle: { label: 'Architectural Style', active: true, assignedTier: 'two', tags: ['improvements']},
    ConstructionType: { label: 'Construction Type', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    FrameType: { label: 'Frame Type', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    ExteriorWallsType: { label: 'Exterior Walls Type', active: true, assignedTier: 'two', tags: ['addSubUnits', 'improvements']},
    InteriorWallsType: { label: 'Interior Walls Type', active: true, assignedTier: 'two', tags: ['improvements']},
    RoofType: { label: 'Roof Type', active: true, assignedTier: 'two', tags: ['improvements']},
    RoofCoverType: { label: 'Roof Cover Type', active: true, assignedTier: 'two', tags: ['improvements']},
    CarStorageType: { label: 'Car Storage Type', active: true, assignedTier: 'two', tags: ['improvements']},
    GarageSpaces: { label: 'Garage Spaces', active: true, assignedTier: 'two', tags: ['improvements']},
    GarageArea: { label: 'Garage Area', active: true, assignedTier: 'two', tags: ['improvements']},
    ParkingSpaces: { label: 'Parking Spaces', active: true, assignedTier: 'two', tags: ['improvements']},
  },
  assessment: {
    AssessedYear: { label: 'Assessed Year', active: true, assignedTier: 'one', tags: ['transfer', 'assessment']},
    AssessedValue: { label: 'Assessed Value', active: true, assignedTier: 'one', tags: ['transfer', 'assessment']},
    AssessedLandValue: { label: 'Assessed Land Value', active: true, assignedTier: 'one', tags: ['transfer', 'assessment']},
    AssessedImprovementValue: { label: 'Assessed Improvement Value', active: true, assignedTier: 'one', tags: ['transfer', 'assessment']},
    // MarketValue: { label: 'Market Value', active: true, assignedTier: 'two', tags: ['improvements']},
    // MarketLandValue: { label: 'Market Land Value', active: true, assignedTier: 'two', tags: ['improvements']},
    // MarketImprovementValue: { label: 'Market Improvement Value', active: true, assignedTier: 'two', tags: ['improvements']},
    // LandValue: { label: 'Land Value', active: true, assignedTier: 'two', tags: ['improvements']},
    // ImprovementsValue: { label: 'Improvements Value', active: true, assignedTier: 'two', tags: ['improvements']},
    AssessorsMapReference: { label: 'Assessors Map Reference', active: true, assignedTier: 'two', tags: ['subdivision', 'rezoning', 'assessment']},
  },
  tax: {
    TaxYear: { label: 'Tax Year', active: true, assignedTier: 'two', tags: ['assessment']},
    TaxAnnualAmount: { label: 'Tax Annual Amount', active: true, assignedTier: 'two', tags: ['assessment']},
    OwnerOccupied: { label: 'Owner Occupied', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionHomestead: { label: 'Tax Exemption Homestead', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionVeteran: { label: 'Tax Exemption Veteran', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionDisabled: { label: 'Tax Exemption Disabled', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionWidow: { label: 'Tax Exemption Widow', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionSenior: { label: 'Tax Exemption Senior', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionSchoolCollege: { label: 'Tax Exemption School/College', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionReligious: { label: 'Tax Exemption Religious', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionWelfare: { label: 'Tax Exemption Welfare', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionPublicUtility: { label: 'Tax Exemption Public Utility', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionCemetery: { label: 'Tax Exemption Cemetery', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionHospital: { label: 'Tax Exemption Hospital', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxExemptionLibrary: { label: 'Tax Exemption Library', active: true, assignedTier: 'two', tags: ['taxExemptionStatus']},
    TaxInitialDeliquencyYear: { label: 'Tax Initial Delinquency Year', active: true, assignedTier: 'two', tags: ['distress']},
  },
  owner1: {
    Owner1OwnershipRights: { label: 'Owner One Ownership Rights', active: true, assignedTier: 'one', tags: ['transfer']},
    Owner1IsCorporation: { label: 'Owner One Is Corporation', active: true, assignedTier: 'one', tags: ['transfer']},
    CorporateIndicator: { label: 'Corporate Indicator', active: true, assignedTier: 'one', tags: ['transfer']},
    Owner1FullName: { label: 'Owner One Full Name', active: true, assignedTier: 'one', tags: ['transfer']},
    Owner1LastName: { label: 'Owner One Last Name', active: true, assignedTier: 'one', tags: ['transfer']},
    Owner1FirstName: { label: 'Owner One First Name', active: true, assignedTier: 'one', tags: ['transfer']},
  },
  owner2: {
    Owner2IsCorporation: { label: 'Owner Two Is Corporation', active: true, assignedTier: 'one', tags: ['transfer']},
    Owner2FullName: { label: 'Owner Two Full Name', active: true, assignedTier: 'one', tags: ['transfer']},
    Owner2LastName: { label: 'Owner Two Last Name', active: true, assignedTier: 'one', tags: ['transfer']},
    Owner2FirstName: { label: 'Owner Two First Name', active: true, assignedTier: 'one', tags: ['transfer']},
  },
  primaryMortgage: {
    PrimaryMortgageAmount: { label: 'Primary Mortgage Amount', active: true, assignedTier: 'one', tags: ['newMortgage']},
    PrimaryMortgageInterestRate: { label: 'Primary Mortgage Interest Rate', active: true, assignedTier: 'one', tags: ['newMortgage']},
    PrimaryLenderName: { label: 'Primary Lender Name', active: true, assignedTier: 'one', tags: ['newMortgage']},
    PrimaryMortgageStartDate: { label: 'Primary Mortgage Start Date', active: true, assignedTier: 'one', tags: ['newMortgage']},
    PrimaryLoanType: { label: 'Primary Loan Type', active: true, assignedTier: 'one', tags: ['newMortgage']},
    PrimaryMortgageTerm: { label: 'Primary Mortgage Term', active: true, assignedTier: 'one', tags: ['newMortgage']},
    PrimaryMortgageDueDate: { label: 'Primary Mortgage Due Date', active: true, assignedTier: 'one', tags: ['newMortgage']},
    TitleCompany: { label: 'Title Company', active: true, assignedTier: 'one', tags: ['newMortgage']},
    OwnershipRights: { label: 'Ownership Rights', active: true, assignedTier: 'one', tags: ['newMortgage']},
    BorrowerRelationship: { label: 'Borrower Relationship', active: true, assignedTier: 'one', tags: ['newMortgage']},
    MortgageTransactionDescription: { label: 'Mortgage Transaction Type', active: true, assignedTier: 'one', tags: ['newMortgage']},
    DeedCategoryDescriprion: { label: 'Deed Category', active: true, assignedTier: 'one', tags: ['newMortgage']},
  },
  secondaryMortgage: {
    SecondaryMortgageAmount: { label: 'Secondary Mortgage Amount', active: true, assignedTier: 'one', tags: ['newMortgage', 'secondMortgage']},
    SecondaryLenderName: { label: 'Secondary Lender Name', active: true, assignedTier: 'one', tags: ['newMortgage', 'secondMortgage']},
    SecondaryMortgageRecordingDate: { label: 'Secondary Mortgage Recording Date', active: true, assignedTier: 'one', tags: ['newMortgage', 'secondMortgage']},
    SecondaryLoanType: { label: 'Secondary Loan Type', active: true, assignedTier: 'one', tags: ['newMortgage', 'secondMortgage']},
    SecondaryMortgageTerm: { label: 'Secondary Mortgage Term', active: true, assignedTier: 'one', tags: ['newMortgage', 'secondMortgage']},
    SecondaryMortgageDueDate: { label: 'Secondary Mortgage Due Date', active: true, assignedTier: 'one', tags: ['newMortgage', 'secondMortgage']},
  },
}

//* recordDetails to map when only Attom data is present
//* 88 rows
const attomDetailsObjAttomOnly = {
  identifiers: {
    FIPS: { label: 'FIPS', currentValue: '', originalValue: '' },
    AttomId: { label: 'Attom ID', currentValue: '', originalValue: '' },
  },
  lot: {
    County: { label: 'County', currentValue: '', originalValue: '' },
    LegalSubdivisionName: { label: 'Legal Subdivision Name', currentValue: '', originalValue: '' },
    ParcelNumber: { label: 'Parcel Number', currentValue: '', originalValue: '' },
    Latitude: { label: 'Latitude', currentValue: '', originalValue: '' },
    Longitude: { label: 'Longitude', currentValue: '', originalValue: '' },
    LotSizeAcres: { label: 'Lot Size Acres', currentValue: '', originalValue: '' },
    LotSizeSquareFeet: { label: 'Lot Size Square Feet', currentValue: '', originalValue: '' },
    Zoning: { label: 'Zoning', currentValue: '', originalValue: '' },
    CountyUseCode: { label: 'County Use Code', currentValue: '', originalValue: '' },
    TaxLot: { label: 'Tax Lot', currentValue: '', originalValue: '' },
    TaxCodeArea: { label: 'Tax Code Area', currentValue: '', originalValue: '' },
    View: { label: 'View', currentValue: '', originalValue: '' },
    CensusTractId: { label: 'Census Tract ID', currentValue: '', originalValue: '' },
  },
  address: {
    StreetAddressOneLine: { label: 'Street Address One Line', currentValue: '', originalValue: '' },
    StreetAddressLine1: { label: 'Street Address Line 1', currentValue: '', originalValue: '' },
    StreetAddressLine2: { label: 'Street Address Line 2', currentValue: '', originalValue: '' },
    StreetNumber: { label: 'Street Number', currentValue: '', originalValue: '' },
    StreetName: { label: 'Street Name', currentValue: '', originalValue: '' },
    City: { label: 'City', currentValue: '', originalValue: '' },
    StateOrProvince: { label: 'StateOrProvince', currentValue: '', originalValue: '' },
    PostalCode: { label: 'Postal Code', currentValue: '', originalValue: '' },
    PostalCodePlus4: { label: 'Postal Code Plus 4', currentValue: '', originalValue: '' },
  },
  summary: {
    PropertyType: { label: 'Property Type', currentValue: '', originalValue: '' },
    PropertySubType: { label: 'Property Sub Type', currentValue: '', originalValue: '' },
    QuitClaimFlag: { label: 'Quit Claim Flag', currentValue: '', originalValue: '' },
    REOflag: { label: 'Foreclosure Flag', currentValue: '', originalValue: '' },
  },
  sale: {
    LastSaleRecordingDate: { label: 'Last Sale Recording Date', currentValue: '', originalValue: '' },
    LastSaleContractDate: { label: 'Last Sale Contract Date', currentValue: '', originalValue: '' },
    LastSaleDate: { label: 'Last Sale Date', currentValue: '', originalValue: '' },
    ClosePrice: { label: 'Close Price', currentValue: '', originalValue: '' },
  },
  living: {
    BuildingAreaTotal: { label: 'Building Area Total', currentValue: '', originalValue: '' },
    GrossArea: { label: 'Gross Area', currentValue: '', originalValue: '' },
    LivingArea: { label: 'Living Area', currentValue: '', originalValue: '' },
    RoomsTotal: { label: 'Rooms', currentValue: '', originalValue: '' },
    BedroomsTotal: { label: 'Bedrooms', currentValue: '', originalValue: '' },
    BathroomsFull: { label: 'Bathrooms Full', currentValue: '', originalValue: '' },
    BathroomsTotalInteger: { label: 'Bathrooms Total', currentValue: '', originalValue: '' },
    Heating: { label: 'Heating', currentValue: '', originalValue: '' },
  },
  building: {
    YearBuilt: { label: 'Year Built', currentValue: '', originalValue: '' },
    YearBuiltEffective: { label: 'Year Built Effective', currentValue: '', originalValue: '' },
    ArchitecturalStyle: { label: 'Architectural Style', currentValue: '', originalValue: '' },
    ConstructionType: { label: 'Construction Type', currentValue: '', originalValue: '' },
    FrameType: { label: 'Frame Type', currentValue: '', originalValue: '' },
    ExteriorWallsType: { label: 'Exterior Walls Type', currentValue: '', originalValue: '' },
    GarageSpaces: { label: 'Garage Spaces', currentValue: '', originalValue: '' },
    GarageArea: { label: 'Garage Area', currentValue: '', originalValue: '' },
    ParkingSpaces: { label: 'Parking Spaces', currentValue: '', originalValue: '' },
  },
  assessment: {
    AssessedValue: { label: 'Assessed Value', currentValue: '', originalValue: '' },
    AssessedLandValue: { label: 'Assessed Land Value', currentValue: '', originalValue: '' },
    AssessedImprovementValue: { label: 'Assessed Improvement Value', currentValue: '', originalValue: '' },
  },
  tax: {
    TaxYear: { label: 'Tax Year', currentValue: '', originalValue: '' },
    TaxAnnualAmount: { label: 'Tax Annual Amount', currentValue: '', originalValue: '' },
    OwnerOccupied: { label: 'Owner Occupied', currentValue: '', originalValue: '' },
  },
  owner1: {
    CorporateIndicator: { label: 'Corporate Indicator', currentValue: '', originalValue: '' },
    Owner1FullName: { label: 'Owner One Full Name', currentValue: '', originalValue: '' },
    Owner1LastName: { label: 'Owner One Last Name', currentValue: '', originalValue: '' },
    Owner1FirstName: { label: 'Owner One First Name', currentValue: '', originalValue: '' },
  },
  owner2: {
    Owner2FullName: { label: 'Owner Two Full Name', currentValue: '', originalValue: '' },
    Owner2LastName: { label: 'Owner Two Last Name', currentValue: '', originalValue: '' },
    Owner2FirstName: { label: 'Owner Two First Name', currentValue: '', originalValue: '' },
  },
  primaryMortgage: {
    PrimaryMortgageAmount: { label: 'Primary Mortgage Amount', currentValue: '', originalValue: '' },
    PrimaryMortgageInterestRate: { label: 'Primary Mortgage Interest Rate', currentValue: '', originalValue: '' },
    PrimaryLenderName: { label: 'Primary Lender Name', currentValue: '', originalValue: '' },
    PrimaryMortgageStartDate: { label: 'Primary Mortgage Start Date', currentValue: '', originalValue: '' },
    PrimaryLoanType: { label: 'Primary Loan Type', currentValue: '', originalValue: '' },
    PrimaryMortgageTerm: { label: 'Primary Mortgage Term', currentValue: '', originalValue: '' },
    PrimaryMortgageDueDate: { label: 'Primary Mortgage Due Date', currentValue: '', originalValue: '' },
    TitleCompany: { label: 'Title Company', currentValue: '', originalValue: '' },
    OwnershipRights: { label: 'Ownership Rights', currentValue: '', originalValue: '' },
    BorrowerRelationship: { label: 'Borrower Relationship', currentValue: '', originalValue: '' },
    MortgageTransactionDescription: { label: 'Mortgage Transaction Type', currentValue: '', originalValue: ''},
    DeedCategoryDescriprion: { label: 'Deed Category', currentValue: '', originalValue: ''},
  },
  secondaryMortgage: {
    SecondaryMortgageAmount: { label: 'Secondary Mortgage Amount', currentValue: '', originalValue: '' },
    SecondaryLenderName: { label: 'Secondary Lender Name', currentValue: '', originalValue: '' },
    SecondaryMortgageRecordingDate: { label: 'Secondary Mortgage Recording Date', currentValue: '', originalValue: '' },
    SecondaryLoanType: { label: 'Secondary Loan Type', currentValue: '', originalValue: '' },
    SecondaryMortgageTerm: { label: 'Secondary Mortgage Term', currentValue: '', originalValue: '' },
    SecondaryMortgageDueDate: { label: 'Secondary Mortgage Due Date', currentValue: '', originalValue: '' },
  },
}
//* recordDetails to map when both Attom and PropMix data sets are present
//* 35 rows
const attomDetailsObjBoth = {
  identifiers: {
    AttomId: { label: 'Attom ID', currentValue: '', originalValue: '' },
  },
  lot: {
    County: { label: 'County', currentValue: '', originalValue: '' },
    CountyUseCode: { label: 'County Use Code', currentValue: '', originalValue: '' },
    TaxCodeArea: { label: 'Tax Code Area', currentValue: '', originalValue: '' },
    View: { label: 'View', currentValue: '', originalValue: '' },
  },
  address: {
    StreetAddressOneLine: { label: 'Street Address One Line', currentValue: '', originalValue: '' },
    StreetAddressLine2: { label: 'Street Address Line 2', currentValue: '', originalValue: '' },
  },
  summary: {
    QuitClaimFlag: { label: 'Quit Claim Flag', currentValue: '', originalValue: '' },
    REOflag: { label: 'Foreclosure Flag', currentValue: '', originalValue: '' },
  },
  sale: {},
  living: {},
  building: {
    FrameType: { label: 'Frame Type', currentValue: '', originalValue: '' },
  },
  assessment: {},
  tax: {},
  owner1: {
    CorporateIndicator: { label: 'Corporate Indicator', currentValue: '', originalValue: '' },
  },
  owner2: {},
  primaryMortgage: {
    PrimaryMortgageAmount: { label: 'Primary Mortgage Amount', currentValue: '', originalValue: '' },
    PrimaryMortgageInterestRate: { label: 'Primary Mortgage Interest Rate', currentValue: '', originalValue: '' },
    PrimaryLenderName: { label: 'Primary Lender Name', currentValue: '', originalValue: '' },
    PrimaryMortgageStartDate: { label: 'Primary Mortgage Start Date', currentValue: '', originalValue: '' },
    PrimaryLoanType: { label: 'Primary Loan Type', currentValue: '', originalValue: '' },
    PrimaryMortgageTerm: { label: 'Primary Mortgage Term', currentValue: '', originalValue: '' },
    PrimaryMortgageDueDate: { label: 'Primary Mortgage Due Date', currentValue: '', originalValue: '' },
    TitleCompany: { label: 'Title Company', currentValue: '', originalValue: '' },
    OwnershipRights: { label: 'Ownership Rights', currentValue: '', originalValue: '' },
    BorrowerRelationship: { label: 'Borrower Relationship', currentValue: '', originalValue: '' },
    MortgageTransactionDescription: { label: 'Mortgage Transaction Type', currentValue: '', originalValue: ''},
    DeedCategoryDescriprion: { label: 'Deed Category', currentValue: '', originalValue: ''},
  },
  secondaryMortgage: {
    SecondaryMortgageAmount: { label: 'Secondary Mortgage Amount', currentValue: '', originalValue: '' },
    SecondaryLenderName: { label: 'Secondary Lender Name', currentValue: '', originalValue: '' },
    SecondaryMortgageRecordingDate: { label: 'Secondary Mortgage Recording Date', currentValue: '', originalValue: '' },
    SecondaryLoanType: { label: 'Secondary Loan Type', currentValue: '', originalValue: '' },
    SecondaryMortgageTerm: { label: 'Secondary Mortgage Term', currentValue: '', originalValue: '' },
    SecondaryMortgageDueDate: { label: 'Secondary Mortgage Due Date', currentValue: '', originalValue: '' },
  },
}

module.exports = { recordDetailsObj, mortgageDataModel, attomDetailsObjAttomOnly, attomDetailsObjBoth };